name: Deploy to NK site

on:
  push:
    branches: [barista-prod]
jobs:
  deploy-to-nk-site:
    runs-on: ubuntu-latest
    steps:
      - name: deploy via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: source deploy-from-gh-actions-to-nk.sh "event-espresso-core"
          host: ${{ secrets.NK_HOST }}
          username: ${{ secrets.NK_USERNAME }}
          passphrase: ${{ secrets.NK_PASSPHRASE }}
          privateKey: ${{ secrets.NK_PRIVATE_KEY}}
